version: '3'

services:
  prom:
    image: prom/prometheus:latest
    restart: always
    container_name: prom
    hostname: prom.north.redislabs-training.org
    environment:
      - storage.tsdb.retention=1d
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/resolv.conf:/etc/resolv.conf
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.21

  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    hostname: grafana.north.redislabs-training.org
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssword
    ports:
      - '3000:3000'
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.22

networks:
  dnscluster_net:
     ipam:
         driver: default
         config:
             - subnet: 172.21.1.0/16
