version: '3'

services:
  n1:
    image: redislabs/redis:latest
    restart: always
    container_name: n1
    hostname: n1.north.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '18070:8070'
      - '21443:8443'
      - '41443:9443'
    volumes:
      - redispersN1:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - redislogN1:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.1

  n2:
    image: redislabs/redis:latest
    restart: always
    container_name: n2
    hostname: n2.north.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '28070:8070'
      - '22443:8443'
      - '42443:9443'
    volumes:
      - redispersN2:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - .edislogN2:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.2

  n3:
    image: redislabs/redis:latest
    restart: always
    container_name: n3
    hostname: n3.north.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '38070:8070'
      - '23443:8443'
      - '43443:9443'
    volumes:
      - redispersN3:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - redislogN3:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.3
  bind:
    restart: always
    image: sameersbn/bind:9.11.3-20190706
    container_name: bind
    hostname: ns.redislabs-training.org
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - ./binddata:/data
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.4

volumes:
  redispersN1:
  redispersN2:
  redispersN3:
  redislogsN1:
  redislogsN2:
  redislogsN3:
networks:
  dnscluster_net:
     ipam:
         driver: default
         config:
             - subnet: 172.21.0.0/16
