version: '3'

services:
  s1:
    image: redislabs/redis:latest
    restart: always
    container_name: s1
    hostname: s1.south.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '48070:8070'
      - '31443:8443'
      - '51443:9443'
    volumes:
      - redispersS1:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - redislogsS1:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.11

  s2:
    image: redislabs/redis:latest
    restart: always
    container_name: s2
    hostname: s2.south.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '58070:8070'
      - '32443:8443'
      - '52443:9443'
    volumes:
      - redispersS2:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - redislogsS2:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.12

  s3:
    image: redislabs/redis:latest
    restart: always
    container_name: s3
    hostname: s3.south.redislabs-training.org
    cap_add:
      - ALL
    ulimits:
      memlock: -1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '58071:8070'
      - '33443:8443'
      - '53443:9443'
    volumes:
      - redispersS3:/var/opt/redislabs/persist
      - ./resolv.conf:/etc/resolv.conf
      - redislogsS3:/var/opt/redislabs
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.13

volumes:
  redispersS1:
  redispersS2:
  redispersS3:
  redislogsS1:
  redislogsS2:
  redislogsS3:
networks:
  dnscluster_net:
     ipam:
         driver: default
         config:
             - subnet: 172.21.1.0/16
