version: '3'

services:
  bind:
    restart: always
    image: sameersbn/bind:9.11.3-20190706
    container_name: bind
    hostname: ns.redislabs-training.org
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - ./binddata:/data
    networks:
      dnscluster_net:
         ipv4_address: 172.21.1.4

networks:
  dnscluster_net:
     ipam:
         driver: default
         config:
             - subnet: 172.21.1.0/16
