docker volume rm dnscluster_redispersN1
docker volume rm dnscluster_redispersN2
docker volume rm dnscluster_redispersN3
docker volume rm dnscluster_redislogsN1
docker volume rm dnscluster_redislogsN2
docker volume rm dnscluster_redislogsN3
